version: '3.9'

services:
  spring-boot-app:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - db

  react-app:
    build: ./realfront
    ports:
      - "3000:80"

  flask-app:
    build: ./NCDSS_flask
    ports:
      - "5000:5000"

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: qwer1234!
      MYSQL_DATABASE: namnam
      MYSQL_USER: namnam
      MYSQL_PASSWORD: qwer1234!
    ports:
      - "3306:3307"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
